var quotes = 
[{"quote":"All of Koons's best art - the encased vacuum cleaners, the stainless-steel Rabbit (the late-twentieth century's signature work of Simulationist sculpture), the amazing gleaming Balloon Dog, and the cast-iron re-creation of a Civil War mortar exhibited last month at the Armory - has simultaneously flaunted extreme realism, idealism, and fantasy.","author":"Jerry Saltz","cat":"amazing"},
{"quote":"Never a tear bedims the eye that time and patience will not dry.","author":"Bret Harte","cat":"patience"},
{"quote":"I had a lot of success from the start. I never really was tested for long periods of time. I got my first professional job while I was a senior in college. I signed with the William Morris Agency before I graduated.","author":"Denzel Washington","cat":"success"},
{"quote":"Catcher in the Rye had a profound impact on me-the idea that we all have lots of dreams that are slowly being chipped away as we grow up.","author":"Judd Nelson","cat":"dreams"},
{"quote":"A writer should get as much education as possible, but just going to school is not enough if it were, all owners of doctorates would be inspired writers.","author":"Gwendolyn Brooks","cat":"education"},
{"quote":"I was the oldest of the children in my family. I had to do a lot of diaper-changing and lunch-making. I was taking my little sister to ballet, picking up my brother, sort of being a super-nanny.","author":"Vin Diesel","cat":"family"},
{"quote":"I watched a lot of silent directors who were absolutely great like John Ford and Fritz Lang, Tod Browning, and also some very modern directors like The Coen Brothers. The directors take the freedom within their own movies to be melodramatic or funny when they chose to be. They do whatever they want and they don't care about the genre.","author":"Michel Hazanavicius","cat":"funny"},
{"quote":"What though youth gave love and roses, Age still leaves us friends and wine.","author":"Thomas More","cat":"age"},
{"quote":"Man falls from the pursuit of the ideal of plan living and high thinking the moment he wants to multiply his daily wants. Man's happiness really lies in contentment.","author":"Mahatma Gandhi","cat":"happiness"},
{"quote":"A few years back, when my style was 'punk grandma,' I picked up an amazing pair of sandals - orthopaedic ones, with really thick soles. I've given them away to a friend now, because these days my look is more '1980s substitute teacher gone wild.'","author":"Beth Ditto","cat":"amazing"},
{"quote":"Of emotions, of love, of breakup, of love and hate and death and dying, mama, apple pie, and the whole thing. It covers a lot of territory, country music does.","author":"Johnny Cash","cat":"death"},
{"quote":"After about the first Millennium, Italy was the cradle of Romanesque architecture, which spread throughout Europe, much of it extending the structural daring with minimal visual elaboration.","author":"Harry Seidler","cat":"architecture"},
{"quote":"With women, I've got a long bamboo pole with a leather loop on the end. I slip the loop around their necks so they can't get away or come too close. Like catching snakes.","author":"Marlon Brando","cat":"women"},
{"quote":"Men must live and create. Live to the point of tears.","author":"Albert Camus","cat":"inspirational"},
{"quote":"And it was back in the mid-1980s, and as I point out in a piece, that was when we are spending about eight percent of our gross domestic product on health care. And even then, we had the impression that so much of the excessive, aggressive medical treatment that took place at the end of life was not only unnecessary but it was cruel.","author":"Richard Dooling","cat":"medical"},
{"quote":"I don't design cars. I'm not a designer. I know what I desire to be built, I know what the end result is, the horsepower, the competition we'll be working against - but I leave it to the people who work with me to put it all together. I don't do anything.","author":"Caroll Shelby","cat":"design"},
{"quote":"Sweat equity is the most valuable equity there is. Know your business and industry better than anyone else in the world. Love what you do or don't do it.","author":"Mark Cuban","cat":"business"},
{"quote":"Marriage, laws, the police, armies and navies are the mark of human incompetence.","author":"Dora Russell","cat":"marriage"},
{"quote":"You can't afford to get sick, and you can't depend on the present health care system to keep you well. It's up to you to protect and maintain your body's innate capacity for health and healing by making the right choices in how you live.","author":"Andrew Weil","cat":"health"},
{"quote":"Happiness is the longing for repetition.","author":"Milan Kundera","cat":"happiness"},
{"quote":"My dad was just a big Joseph Campbell nut.","author":"Trey Parker","cat":"dad"},
{"quote":"Manners are like the shadows of virtues, they are the momentary display of those qualities which our fellow creatures love and respect.","author":"Sydney Smith","cat":"respect"},
{"quote":"I mean, I was born the day war broke out, but I don't remember all the bombs though they did actually break up Liverpool, you know. I remember when I was a little older, there was big gaps in all the streets where houses used to be. We used to play over them.","author":"Ringo Starr","cat":"war"},
{"quote":"As a kid, I did want to be an old-timer, since they were the ones with the big stories and the cool clothes. I wanted to go there. Now, I guess I want to bring that with me and go back in time.","author":"Tom Waits","cat":"cool"},
{"quote":"I'm a role model now. I didn't know I was gonna have 13-year-old fans, so I've tried to change a few things here and there. But I also know that the girls don't want me to be Miley Cyrus, either.","author":"Nicki Minaj","cat":"change"},
{"quote":"My mother was making $135 a week, but she had resilience and imagination. She might take frozen vegetables, cook them with garlic, onion and Spam, and it would taste like a four-star dinner.","author":"Andre Dubus III","cat":"imagination"},
{"quote":"After climbing a great hill, one only finds that there are many more hills to climb.","author":"Nelson Mandela","cat":"great"},
{"quote":"When the going gets weird, the weird turn pro.","author":"Hunter S. Thompson","cat":"sports"},
{"quote":"The weak can never forgive. Forgiveness is the attribute of the strong.","author":"Mahatma Gandhi","cat":"forgiveness"},
{"quote":"Support by United States rulers is rather in the nature of the support that the rope gives to a hanged man.","author":"Nikita Khrushchev","cat":"nature"},
{"quote":"Literature is the expression of a feeling of deprivation, a recourse against a sense of something missing. But the contrary is also true: language is what makes us human. It is a recourse against the meaningless noise and silence of nature and history.","author":"Octavio Paz","cat":"history"},
{"quote":"In my opinion, the most significant works of the twentieth century are those that rise beyond the conceptual tyranny of genre they are, at the same time, poetry, criticism, narrative, drama, etc.","author":"Juan Goytisolo","cat":"poetry"},
{"quote":"Leadership is the key to 99 percent of all successful efforts.","author":"Erskine Bowles","cat":"leadership"},
{"quote":"That some achieve great success, is proof to all that others can achieve it as well.","author":"Abraham Lincoln","cat":"great"},
{"quote":"I know it's a cliche but I never wanted to be famous. I don't believe anybody wants to be famous.","author":"Jeremy Renner","cat":"famous"},
{"quote":"This war is not about slavery.","author":"Robert E. Lee","cat":"war"},
{"quote":"I thought, after the Pulitzer, at least nothing will surprise me quite that much in my life. And another one happened. It was quite amazing.","author":"Rita Dove","cat":"amazing"},
{"quote":"I realize that patriotism is not enough. I must have no hatred or bitterness towards anyone.","author":"Edith Cavell","cat":"patriotism"},
{"quote":"We must return to nature and nature's god.","author":"Luther Burbank","cat":"environmental"},
{"quote":"If faith produce no works, I see That faith is not a living tree. Thus faith and works together grow, No separate life they never can know. They're soul and body, hand and heart, What God hath joined, let no man part.","author":"Hannah More","cat":"faith"},
{"quote":"Marriage is a gamble, let's be honest.","author":"Yoko Ono","cat":"marriage"},
{"quote":"You know you're getting old when the candles cost more than the cake.","author":"Bob Hope","cat":"birthday"},
{"quote":"I realize myself that hate wastes a lot of time and energy and I would rather re-direct any energy that I have to good and positive use.","author":"Julian Cope","cat":"positive"},
{"quote":"Friends are thieves of time.","author":"Francis Bacon","cat":"time"},
{"quote":"What I like to do is just make good music, good movies, hopefully perform a good show full of energy and just have some fun.","author":"LL Cool J","cat":"movies"},
{"quote":"Before you, I engage myself to serve my country with the devotion and the exemplary that this post demands. I understand responsibilities of the job and, as such, I give a republican salute to Nicolas Sarkozy who has led France for 5 years and who deserves all of our respect.","author":"Francois Hollande","cat":"respect"},
{"quote":"John wrote with a very deep love for the human race and a concern for its future.","author":"Yoko Ono","cat":"future"},
{"quote":"When I was a teenager I would lock myself in the bathroom for hours, bouffanting my hair like Patty Duke and trying to recreate Barbra Streisand's flawless eyeliner, only to comb it all out and wash it all off before stepping out into the world a butchish bisexual teen.","author":"Beth Ditto","cat":"teen"},
{"quote":"Next to acquiring good friends, the best acquisition is that of good books.","author":"Charles Caleb Colton","cat":"best"},
{"quote":"Perhaps there is an idea among Japanese students that one general difference between Japanese and Western poetry is that the former cultivates short forms and the latter longer ones, gut this is only in part true.","author":"Lafcadio Hearn","cat":"poetry"},
{"quote":"Anybody can become angry - that is easy, but to be angry with the right person and to the right degree and at the right time and for the right purpose, and in the right way - that is not within everybody's power and is not easy.","author":"Aristotle","cat":"anger"},
{"quote":"I guess John Lennon had it right: give peace a chance.","author":"Chris O'Donnell","cat":"peace"},
{"quote":"The more you get into any religion, it becomes the same. It really becomes how you treat other people and how you get outside yourself. How you look to help other people, and how you get out of this 'I, me, mine' type of thing.","author":"Abel Ferrara","cat":"religion"},
{"quote":"My home town is very small and very remote and we don't have a movie house.","author":"Tommy Lee Jones","cat":"home"},
{"quote":"Technological society has succeeded in multiplying the opportunities for pleasure, but it has great difficulty in generating joy.","author":"Pope Paul VI","cat":"society"},
{"quote":"I need, absolutely, to be alone.","author":"Jeanne Moreau","cat":"alone"},
{"quote":"I'd like to believe an accumulation of experience has made me a sort of a grown-up person, so I can have judgment and taste and whatever.","author":"Maurice Sendak","cat":"experience"},
{"quote":"This has always been the way of presidential politics. The president rises above the fray while his surrogates go on the attack. They throw the spears and fling the mud he sits upon the throne.","author":"John Podhoretz","cat":"politics"},
{"quote":"You live in this shadow that you're going to burn in Hell until you're saved. And I still worry about it a little. I don't believe in Heaven, but I do still fear Hell.","author":"Beth Ditto","cat":"fear"},
{"quote":"All men are somewhat ridiculous and grotesque, just because they are men and in this respect artists might well be regarded as man multiplied by two. So it is, was, and shall be.","author":"Karl Wilhelm Friedrich Schlegel","cat":"respect"},
{"quote":"Well, I have a sister that I'm very close with, and that relationship is probably the most intense relationship of my life to date, probably of my life, period.","author":"Zoe Kazan","cat":"relationship"},
{"quote":"I'm essentially a momma's boy with a good education.","author":"Tom Sizemore","cat":"education"},
{"quote":"Music is a moral law. It gives soul to the universe, wings to the mind, flight to the imagination, and charm and gaiety to life and to everything.","author":"Plato","cat":"imagination"},
{"quote":"I was taught from a young age that I had to serve, so that turned into me thinking I had to save the planet.","author":"Alanis Morissette","cat":"age"},
{"quote":"The distinctions of fine art bore me to death.","author":"Maurice Sendak","cat":"death"},
{"quote":"So I'd be quite happy to have a three-hour Lincoln-Douglas-style debate with Barack Obama. I'd let him use a teleprompter. I'll just rely on knowledge. We'll do fine.","author":"Newt Gingrich","cat":"knowledge"},
{"quote":"This means that to entrust to science - or to deliberate control according to scientific principles - more than scientific method can achieve may have deplorable effects.","author":"Friedrich August von Hayek","cat":"science"},
{"quote":"If you're 40 years old and you've never had a failure, you've been deprived.","author":"Gloria Swanson","cat":"failure"},
{"quote":"The president has declared that the debate over government-controlled health care is over. That will come as news to the millions of Americans who will elect Mitt Romney so we can repeal Obamacare.","author":"Paul Ryan","cat":"health"},
{"quote":"Of course, nobody would deny the importance of human beings for theological thinking, but the time span of history that theologians think about is a few thousand years of human culture rather than the fifteen billion years of the history of the universe.","author":"John Polkinghorne","cat":"history"},
{"quote":"Traits like humility, courage, and empathy are easily overlooked - but it's immensely important to find them in your closest relationships.","author":"Laura Linney","cat":"courage"},
{"quote":"There is so much of good in human nature that men grow to like each other upon better acquaintance, and this points to another way in which we may strive to promote the peace of the world.","author":"Elihu Root","cat":"peace"},
{"quote":"I'm a big sports fan in general.","author":"Luke Bryan","cat":"sports"},
{"quote":"Only one thing has to change for us to know happiness in our lives: where we focus our attention.","author":"Greg Anderson","cat":"happiness"},
{"quote":"Every major food company now has an organic division. There's more capital going into organic agriculture than ever before.","author":"Michael Pollan","cat":"food"},
{"quote":"I love the music of Lauryn Hill and Erykah Badu and more recently the music of Laura Marling. All these women share a strength and a wisdom in their voices and music that really makes me want to make music and sing.","author":"Lianne La Havas","cat":"strength"},
{"quote":"It's incredible that they censor films. It's sad.","author":"Dario Argento","cat":"sad"},
{"quote":"If your house is burning, wouldn't you try and put out the fire?","author":"Imran Khan","cat":"home"},
{"quote":"In health there is freedom. Health is the first of all liberties.","author":"Henri Frederic Amiel","cat":"freedom"},
{"quote":"Choreography is mentally draining, but there's a pleasure in getting into the studio with the dancers and the music.","author":"Alvin Ailey","cat":"music"},
{"quote":"Every man's life ends the same way. It is only the details of how he lived and how he died that distinguish one man from another.","author":"Ernest Hemingway","cat":"life"},
{"quote":"It was the full conviction of this, and of what could be done, if every man were placed in the office for which he was fitted by nature and a proper education, which first suggested to me the plan of Illumination.","author":"Adam Weishaupt","cat":"education"},
{"quote":"We're still in the first minutes of the first day of the Internet revolution.","author":"Scott Cook","cat":"technology"},
{"quote":"Character, in the long run, is the decisive factor in the life of an individual and of nations alike.","author":"Theodore Roosevelt","cat":"life"},
{"quote":"Caring for but never trying to own may be a further way to define friendship.","author":"William Glasser","cat":"friendship"},
{"quote":"I am for gay marriage. Or same-sex marriage. I don't want to say it the wrong way. I think people are sensitive to it. I have been painted as being this right-wing zealot on choice. Nothing could be further from the truth.","author":"Harold Ford","cat":"marriage"},
{"quote":"With 'The Host,' I think the actors could be really big names. That would be cool. I'd love to see Robert Redford put on a beard and be Jeb he would be amazing... Matt Damon has some very Jared-esque qualities, and then Casey Affleck as Ian and Ben Affleck as Kyle. Imagine the interplay.","author":"Stephenie Meyer","cat":"amazing"},
{"quote":"Without health life is not life it is only a state of langour and suffering - an image of death.","author":"Buddha","cat":"death"},
{"quote":"There are many victories worse than a defeat.","author":"George Eliot","cat":"fear"},
{"quote":"We do not consider patriotism desirable if it contradicts civilized behavior.","author":"Friedrich Durrenmatt","cat":"patriotism"},
{"quote":"Faith makes all things possible... love makes all things easy.","author":"Dwight L. Moody","cat":"faith"},
{"quote":"I believe in education and wish I had a better one.","author":"Loretta Lynn","cat":"education"},
{"quote":"I hope that I would be considered romantic. I don't know... one of my favorite movies is 'The Notebook' so I guess that would be considered romantic. But I think being romantic is more than the flowers and the gifts. It's about connecting with the person and being able to talk and share things with her.","author":"Taylor Lautner","cat":"hope"},
{"quote":"We have such a long, familiar history with Peter Falk. The minute his mug is on that screen people smile.","author":"Paul Reiser","cat":"smile"},
{"quote":"One can survive everything, nowadays, except death, and live down everything except a good reputation.","author":"Oscar Wilde","cat":"death"},
{"quote":"It's really hard for me to sometimes put myself out there, like 'Hey, how do you feel about making music together?' because maybe I'm afraid of rejection or I don't want to put anybody out. It's the Southerner in me, like, 'I don't mean to bother you but do you mind making a song?'","author":"Beth Ditto","cat":"music"},
{"quote":"Experience is the teacher of all things.","author":"Julius Caesar","cat":"experience"},
{"quote":"I think that is where poetry reading becomes such an individual thing. I mean I have friend who like poets who just don't say anything to me at all, I mean they seem to me rather ordinary and pedestrian.","author":"James Laughlin","cat":"poetry"},
{"quote":"Christianity is not the faith of the complacent, the comfortable or of the timid. It demands and creates heroic souls like Wesley, Wilberforce, Bonhoeffer, John Paul the Second, and Billy Graham. Each showed, in their own way, the relentless and powerful influence of the message of Jesus Christ.","author":"Mitt Romney","cat":"faith"},
{"quote":"In truth, I am a single mother. But I don't feel alone at all in parenting my daughter. Krishna has a whole other side of her family who loves her, too. And so Krishna is parented by me, but also by her grandmother and aunts and cousins and uncles and friends.","author":"Padma Lakshmi","cat":"alone"}];